name: CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: CD
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Docker Compose Start
      run: docker-compose -f ./docker-compose.yml up -d

    - name: application.yml Create
      run: |
        mkdir ./src/main/resources
        touch ./src/main/resources/application.yml
        echo "${{ secrets.STARTSPRING }}" > ./src/main/resources/application.yml
        cat ./src/main/resources/application.yml
      shell: bash

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash

    - name: Build With Gradle
      run: ./gradlew clean build
      shell: bash

    - name: Docker image build
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/github-action-demo .

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/github-action-demo

    - name: Deploy to prod
      uses: appleboy/ssh-action@master
      id: deploy-prod
      with:
        host: ${{ secrets.HOST_PROD }}
        username: ubuntu
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        port: 22
        script: |
          sudo docker ps 
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/github-action-demo
          sudo docker run -d -p 8080:8090 ${{ secrets.DOCKER_USERNAME }}/github-action-demo
          sudo docker image prune -f
          

      
